#!/usr/bin/env bash

if
  [[ -s "/home/systemadmin/.rvm/gems/ruby-2.3.0/environment" ]]
then
  source "/home/systemadmin/.rvm/gems/ruby-2.3.0/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/systemadmin/.rvm/gems/ruby-2.3.0/environment'" >&2
  exit 1
fi
